---
- hosts: staging
  become: true
  user: root
  roles: 
    - lemp
    - node
    - git
    - staging

- hosts: production
  become: true
  user: root
  roles:
    - lemp
    - node
    - git
    - production

- hosts: jenkins
  become: true
  user: root
  roles:
    - jenkins